import React from 'react';
import { Dashboard as DashboardLayout } from 'layouts';
import styles from './styles';
import { Grid, Container, withStyles } from '@material-ui/core';



function TermsOfUse(props) {
    const { classes } = props;
    return (
            <div>
                <DashboardLayout title="TERMS OF USE">
                        <Grid className={classes.content} xs={12} >
                            <Container maxWidth="md">
                                <p><strong>Introduction</strong></p>
                                <p><span className={classes.fontWeight}>Welcome to RITSWORLD, a software created by RITSWORLD BUSINESS SOLUTIONS Private Limited, that helps you in following your lead, delight your customer and save data and reminder. This service is complete property of RITSWORLD BUSINESS SOLUTIONS Private Limited. Please read through the following Terms of Use carefully, since it contains important information about your legal rights, obligations and remedies. The Terms of Use also contain limitations and exclusions and a dispute resolution clause that governs how disputes shall be resolved.</span></p>
                                <p><span className={classes.fontWeight}>Together with RITSWORLD&rsquo;s Privacy Policy these Terms of Use govern your access to and use of RITSWORLD. This is a legal agreement between you and RITSWORLD. By accessing or using the RITSWORLD, you (the "User") indicate that you have read, understand and agree to be bound by these Terms of Use. If you do not accept these Terms of Use in their entirety, please stop accessing or use.</span></p>
                                <p><span className={classes.fontWeight}>&nbsp;</span></p>
                                <p><strong>Modification of the RITSWORLD or Terms of Use</strong></p>
                                <p><span className={classes.fontWeight}>RITSWORLD reserves the right at its sole discretion to modify, discontinue or terminate, or to change, add or to or remove portions of these Terms of Use at any time without further notice. If RITSWORLD does this, it will post the revised Terms of Use on this page and it will indicate the date that these terms were last revised at the top of this page. The revised Terms of Use shall be effective immediately after they are posted on the Site (unless a longer notice period is required by law). After any such changes, your continued use of the site and mobile app implies your acceptance of the new Terms of Use. If you do not agree to these or any future Terms of Use, please do not continue to use or access the site and mobile app. It is your responsibility to regularly check the site and mobile app to determine if there have been changes to these Terms of Use and to review such changes.</span></p>
                                <p><strong>Registration Content</strong></p>
                                <p><span className={classes.fontWeight}>You may access and use the Product and Content for your own personal commercial use. You will not remove, alter or conceal any copyright, trademark, service mark or other proprietary rights notices incorporated in or accompanying the site, Content, User Content without prior written permission. RITSWORLD and its licensors own all right, title and interest, including all worldwide intellectual property rights, Content and the trademarks, service marks and logos contained therein other than your User Content.</span></p>
                                <p><strong>User Content</strong></p>
                                <p><span className={classes.fontWeight}>You are solely responsible for the content that you submit to the software, or transmit to other</span></p>
                                <p><span className={classes.fontWeight}>RITSWORLD does not claim intellectual property rights over the User Data including contacts and address book data and other data you upload to the Service. Your User Data uploaded remains yours. RITSWORLD will not re-distribute, publish or disclose publicly any uploaded User Data unless required by law.</span></p>
                                <p><span className={classes.fontWeight}>RITSWORLD does not automatically review all User Data uploaded, but has the right (but not the obligation) in their sole discretion to refuse or remove any User Data that is available via the Service.</span></p>
                                <p><strong>Technical Support</strong></p>
                                <p><span className={classes.fontWeight}>Technical support is only provided to paid subscribers and is only available via email.</span></p>
                                <p><strong>Termination and Cancellation</strong></p>
                                <p><span className={classes.fontWeight}>You may terminate your RITSWORLD account at any time and for any reason by navigating to the User Profile Page and clicking on Cancel Account. An email or phone call to RITSWORLD does not constitute a valid and accepted form of cancellation. Upon Cancellation, all of your User Data will be deleted from RITSWORLD servers and cannot be recovered.</span></p>
                                <p><span className={classes.fontWeight}>Any termination or suspension shall not affect your obligations to RITSWORLD under these Terms of Use (including but not limited to ownership, indemnification and limitation of liability), which shall survive termination or suspension.</span></p>
                                <p>&nbsp;</p>
                                <p><strong>Currency of the Site</strong></p>
                                <p><span className={classes.fontWeight}>RITSWORLD updates the information on the site and mobile app regularly. However, RITSWORLD cannot guarantee or accept any responsibility or liability for the accuracy, currency or completeness of the information on the site and mobile app. RITSWORLD may revise, supplement or delete information, services and/or the resources contained in the site and mobile app and reserves the right to make such changes without prior notification to past, current or prospective visitors.</span></p>
                                <p><strong>Internet software or computer viruses</strong></p>
                                <p><span className={classes.fontWeight}>Due to technical difficulties with the Internet, Internet software or transmission problems could produce inaccurate or incomplete copies of information contained on the Site. Computer viruses or other destructive programs may also be inadvertently downloaded from the Site.</span></p>
                                <p><span className={classes.fontWeight}>RITSWORLD shall not be responsible or liable for any software, computer viruses or other destructive, harmful or disruptive files or programs that may infect or otherwise impact your use of your computer equipment or other property on account of your access to, use of, or browsing on the Site or your downloading of any of the Materials from the Web Site. RITSWORLD recommends that you install appropriate anti-virus or other protective software.</span></p>
                                <p><strong>User Conduct</strong></p>
                                <p><span className={classes.fontWeight}>RITSWORLD wants to promote an environment where Users can safely interact with each other. You agree not to do any of the following while accessing or using the Software:</span></p>
                                <ol>
                                <li><span className={classes.fontWeight}> falsely represent yourself, impersonate another person or entity, or create a false identity on the Site;</span></li>
                                <li><span className={classes.fontWeight}> use or try to use pirated copy (without written permission fromRITSWORLD);</span></li>
                                <li><span className={classes.fontWeight}> asking for the any other user&rsquo;s customer&rsquo;s detail;</span></li>
                                <li><span className={classes.fontWeight}> circumvent, disable or otherwise interfere with security related features of the Site or features that prevent or restrict use or copying of any Content;</span></li>
                                <li><span className={classes.fontWeight}> intimidate or harass other Users;</span></li>
                                <li><span className={classes.fontWeight}> submit or transfer content, in the sole judgment of RITSWORLD, which is objectionable or inhibits another User from effectively using the Site, or which may expose RITSWORLD or its Users to harm or liability;</span></li>
                                <li><span className={classes.fontWeight}> submit or store any content that RITSWORLD deems to be harmful, threatening, unlawful, defamatory, infringing, abusive, inflammatory, harassing, vulgar, obscene, fraudulent, invasive of privacy or publicity rights, hateful, or racially, ethnically or otherwise objectionable;</span></li>
                                <li><span className={classes.fontWeight}> submit or store any content that RITSWORLD deems to be harmful, threatening, unlawful, defamatory, infringing, abusive, inflammatory, harassing, vulgar, obscene, fraudulent, invasive of privacy or publicity rights, hateful, or racially, ethnically or otherwise objectionable;</span></li>
                                <li><span className={classes.fontWeight}> use the Site in any unlawful manner or in any other manner that could damage, disable, overburden or impair the Site</span></li>
                                <li><span className={classes.fontWeight}> attempt to decipher, decompile, disassemble or reverse engineer any of the software used to provide the Site.</span></li>
                                </ol>
                                <p><strong>Arbitration</strong></p>
                                <p><span className={classes.fontWeight}>You and RITSWORLD agree that except as otherwise stated, the sole and exclusive forum and remedy for any dispute and claim relating to or arising out of these Terms of Use, the Software shall be final and binding arbitration. To the extent that either of us has in any manner infringed upon or violated the other party's patent, copyright, trademark or trade secret rights, or you have otherwise violated any of the user conduct rules set forth, then the parties acknowledge that arbitration is not an adequate remedy and that injunctive or other appropriate relief may be sought.</span></p>
                                <p><strong>Disclaimers</strong></p>
                                <p><span className={classes.fontWeight}>Your use of the Software, Content, User Content and processing of User Data is at your sole discretion and risk. The Software, Content, User Content and the processing of User Data, and all materials, information, products and services included therein, are provided on an "AS IS" and "AS AVAILABLE" basis without warranties of any kind. RITSWORLD EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND, EXPRESS, IMPLIED OR STATUTORY, RELATING TO THE SOFTWARE, CONTENT AND USER DATA, INCLUDING WITHOUT LIMITATION THE WARRANTIES OF TITLE, MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT OF PROPRIETARY RIGHTS, COURSE OF DEALING OR COURSE OF PERFORMANCE. RITSWORLD disclaims any warranties:</span></p>
                                <p>&nbsp;</p>
                                <p><span className={classes.fontWeight}>(i) regarding the security, accuracy, reliability, timeliness and performance of the software; or</span></p>
                                <p><span className={classes.fontWeight}>(ii) that the Software, Content, User Content and User Data will be error-free or that any errors will be corrected. No advice or information, whether oral or written, obtained by you from RITSWORLD, shall create any warranty not expressly stated in this Agreement. Some states or jurisdictions do not allow the exclusion of certain warranties. Accordingly, some of the above exclusions may not apply to you.</span></p>
                                <p><strong>Indemnification and Limitation of Liability</strong></p>
                                <p><span className={classes.fontWeight}>You agree to defend, indemnify, and hold RITSWORLD and Avinashi Ventures Private Limited, its officers, directors, employees and agents, subsidiaries and affiliates, and each of their officers, directors, employees and agents, harmless from and against any loss, liability, claim, demand, damages, costs and expenses, including, without limitation, reasonable attorney's fees, arising out of or in any way connected with</span></p>
                                <p>&nbsp;</p>
                                <p><span className={classes.fontWeight}>(i) your access to or use of the RITSWORLD, Content, User Content and processing of User Data;</span></p>
                                <p><span className={classes.fontWeight}>(ii) your violation of these Terms of Use;</span></p>
                                <p><span className={classes.fontWeight}>(iii) your violation of any third party right, including without limitation any intellectual property right, property, or privacy right.</span></p>
                                <p><strong>Indemnification and Limitation of Liability</strong></p>
                                <p><span className={classes.fontWeight}>You agree to defend, indemnify, and hold RITSWORLD and Avinashi Ventures Private Limited, its officers, directors, employees and agents, subsidiaries and affiliates, and each of their officers, directors, employees and agents, harmless from and against any loss, liability, claim, demand, damages, costs and expenses, including, without limitation, reasonable attorney's fees, arising out of or in any way connected with</span></p>
                                <p>&nbsp;</p>
                                <p><span className={classes.fontWeight}>(i) your access to or use of the RITSWORLD, Content, User Content and processing of User Data;</span></p>
                                <p><span className={classes.fontWeight}>(ii) your violation of these Terms of Use;</span></p>
                                <p><span className={classes.fontWeight}>(iii) your violation of any third party right, including without limitation any intellectual property right, property, or privacy right.</span></p>
                                <p><span className={classes.fontWeight}>You acknowledge that RITSWORLD's entire liability and your exclusive remedy with respect to service warranty shall be RITSWORLD using commercially reasonable efforts to correct non-conformities. EXCEPT FOR THE ABOVE EXPRESS LIMITED WARRANTY, RITSWORLD MAKES AND YOU RECEIVE NO WARRANTIES, EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, AND RITSWORLD SPECIFICALLY DISCLAIMS ANY IMPLIED WARRANTIES OF MERCHANTABILITY, NONINFRINGEMENT AND FITNESS FOR A PARTICULAR PURPOSE WITH RESPECT TO THE RITSWORLD OFFERING. RITSWORLD DOES NOT WARRANT THAT THE RITSWORLD OFFERINGS WILL MEET YOUR REQUIREMENTS OR THAT THE RITSWORLD OFFERINGS WILL BE ERROR FREE. This limitation or exclusion of warranties may be subject to exceptions in local jurisdictions.</span></p>
                                <p><span className={classes.fontWeight}>Certain state laws do not allow limitations on implied warranties or the exclusion or limitation of certain damages. If these laws apply to you, some or all of the above disclaimers, exclusions or limitations may not apply, and you may have additional rights.</span></p>
                                <p><strong>Applicable Law</strong></p>
                                <p><span className={classes.fontWeight}>The RITSWORLD is controlled, operated and administered by RITSWORLD from within the State of Gujarat, in India. The Software can be accessed from all states and territories of the India, as well as from other countries around the world. As each of these jurisdictions has laws that may differ from those of Gujarat, by accessing the Software, you acknowledge and agree that all matters relating to access to, or use of the RITSWORLD shall be governed by the laws of the State of Gujarat and the federal laws of the India applicable therein (without reference to conflicts of laws principles).</span></p>
                                <p><strong>Other</strong></p>
                                <p><span className={classes.fontWeight}>These Terms of Use constitute the entire agreement between you and RITSWORLD concerning the use of the Software, and supersedes any prior agreement between you and RITSWORLD relating to your use of the Site. RITSWORLD&rsquo;&rsquo;s failure to exercise or enforce any right or provision of these Terms of Use shall not constitute a waiver of this right or provision in this or any other instance. If any provision of this Terms of Use is held to be invalid, the remainder of this Agreement shall continue in full force and effect. If any provision of these Terms of Use shall be deemed unlawful, void or unenforceable, that provision shall be deemed severable from these Terms of Use but shall not affect the validity and enforceability of the remaining provisions.</span></p>
                                <p><strong>Feedback</strong></p>
                                <p><span className={classes.fontWeight}>RITSWORLD welcomes your feedback. You may submit feedback by emailing us at admin@ritsworld.com. You acknowledge and agree that any questions, comments, suggestions, ideas, or other information about the Site ("Feedback") provided by you to RITSWORLD or any of its employees or representatives are non-confidential. RITSWORLD shall own a non-exclusive license to the unlimited use of the Feedback, including without limitation the right to reformat and translate it, for commercial or other purposes and its dissemination without acknowledgment or compensation to you.</span></p>
                                <p><strong>Questions</strong></p>
                                <p><span className={classes.fontWeight}>If you have questions about these Terms of Use or about the Services, please contact RITSWORLD at </span><span className={classes.fontWeight}>admin@ritsworld.com</span></p>
                            </Container>
                        </Grid>
                </DashboardLayout>
            </div>
        )
    
}

export default withStyles(styles)(TermsOfUse);